# numpy

## 작업 시간 비교

In [1]:
import numpy as np
import datetime
#list 생성
li = range(1,1000000)
#현재 시간 저장 및 출력
s = datetime.datetime.now()
print("리스트 작업 시작 시간:", s)
#li의 각 요소에 10을 곱하기
for i in li:
    i = i * 10
s = datetime.datetime.now()
print("리스트 작업 종료 시간:", s)

#ndarray 생성
ar = np.arange(1,1000000)
s = datetime.datetime.now()
print("ndarray 작업 시작 시간:", s)
ar = ar * 10
s = datetime.datetime.now()
print("ndarray 작업 종료 시간:", s)

리스트 작업 시작 시간: 2022-02-09 07:19:22.693358
리스트 작업 종료 시간: 2022-02-09 07:19:22.775446
ndarray 작업 시작 시간: 2022-02-09 07:19:22.778934
ndarray 작업 종료 시간: 2022-02-09 07:19:22.782779


## 배열 생성 과 속성 확인

In [2]:
import numpy
#list를 이용해서 array 생성
ar = numpy.array([1, 2, 3])

##생성된 데이터의 자료형 확인
print(type(ar)) 

#차원 확인 - 1차원 3개의 데이터로 구성
print (ar.shape) 

#2차원 배열 만들기
br = numpy.array([[1,2,3],[4,5,6]]) 

#배열 출력
print(br)

#배열의 차원 확인
print (br.shape) 

#배열의 메모리 크기 확인
print(br.nbytes)

<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
48


## ndarray 의 생성

In [3]:
import numpy
# 1차원 배얼 [0,1,2, ... ,9] 생성
ar = numpy.arange(10)
print(ar)
print()

# start, end, num-points
ar = numpy.linspace(0, 1, 6)  
print(ar)
print()

# start, end, num-points, 마지막 포인트는 제외
ar = numpy.linspace(0, 1, 5, endpoint=False)
print(ar)
print()

[0 1 2 3 4 5 6 7 8 9]

[0.  0.2 0.4 0.6 0.8 1. ]

[0.  0.2 0.4 0.6 0.8]



## 특수 행렬

In [4]:
import numpy
b1 = numpy.ones(10) # 1로 채원진 10 크기의 (1차원) 배열 생성
print(b1)
print()

b2 = numpy.zeros((5,5)) # 0으로 채원진 5x5 크기의 배열 생성
print(b2)
print()

#2*2 단위 행렬 생성
ar = numpy.eye(2, dtype=int)
print(ar)
print()

#3*3 행렬을 만들고 가운데에서 대각선 방향으로 위쪽에 1을 채움
ar = numpy.eye(3, k=1)
print(ar)
print()

#3*4 행렬을 만들고 가운데에서 대각선 방향으로 위쪽에 1을 채움
ar = numpy.eye(3, M=4, k=1)
print(ar)
print()

#9개짜리 일차원 배열을 3*3행렬로 변환
ar = numpy.arange(9).reshape((3,3))
print(ar)
print()

br = numpy.diag(ar)
print(br)
print()

#중앙의 대각선에서 위나 아래 한칸 이동해서 데이터를 가져와서 벡터를 생성
cr = numpy.diag(ar,k=1)
print(cr)
print()

dr = numpy.diag(ar, k=-1)
print(dr)
print()

er = numpy.empty( (2,2) ) # 가비지 값으로 채원진 2x2 크기의 배열 생성
print(er)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1 0]
 [0 1]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 4 8]

[1 5]

[3 7]

[[5.e-324 0.e+000]
 [0.e+000 5.e-324]]


## ndarray 의 자료형

In [5]:
import numpy as np
#정수로만 구성
ar = np.array([1,2,3])
print("타입 확인:",ar.dtype);

#문자열로만 구성
ar = np.array(['12', '2' ,'3'])
print("타입 확인:",ar.dtype);

#정수와 실수 혼합
ar = np.array([3, 2.9, 4])
print("타입 확인:",ar.dtype);

#문자열과 숫자 혼합
ar = np.array([3, 2.9, '4'])
print("타입 확인:",ar.dtype);

#문자열과 정수 혼합이지만 정수로 설정
ar = np.array([3, 2, '4'], dtype=np.int32)
print("타입 확인:",ar.dtype);

#실수 타입으로 변경
ar = ar.astype(np.string_)
print("타입 확인:",ar.dtype);

타입 확인: int64
타입 확인: <U2
타입 확인: float64
타입 확인: <U32
타입 확인: int32
타입 확인: |S11


## 행렬 구조 변환

In [6]:
import numpy
# 1차원 배열 [0,1,2, ... ,9] 생성
ar = numpy.arange(10)  
print(ar)
print()

# 같은 요소를 가지고 2x5 배열로 변형
ar = ar.reshape(2, 5)
print(ar)
print()

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]



In [7]:
import numpy
# 행렬을 생성
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#1차원으로 변환 - 모양만 변경
ar = matrix.reshape(-1)
print(ar)
print()

#1차원으로 변환 - 데이터를 복제
br = matrix.flatten()
print(br)
print()

#원본 데이터 변경
matrix[0,0] = 100

#원본이 변경되었으므로 같이 변경됨 
print(ar)
print()

#복제를 했으므로 아무런 영향이 없음 
print(br)

[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]

[100   2   3   4   5   6   7   8   9]

[1 2 3 4 5 6 7 8 9]


## 인덱싱

In [8]:
import numpy as np

# 하나의 행을 갖는 배열 생성
vector = np.array([1, 2, 3, 4, 5, 6])

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# vector의 세 번째 원소를 선택합니다.
print(vector[2])
print()

# matrix의 두 번째 행, 두 번째 열의 원소를 선택합니다.
print(matrix[1,1])
print()

# 벡터에 있는 모든 원소를 선택합니다.
print(vector[:])
print()

# 세 번째 원소를 포함하여 그 이전의 모든 원소를 선택합니다.
print(vector[:3])
print()

# 세 번째 이후의 모든 원소를 선택합니다.
print(vector[3:])
print()

# 마지막 원소를 선택합니다.
print(vector[-1])
print()

# 행렬에서 첫 번째 두 개의 행과 모든 열을 선택합니다.
print(matrix[:2,:])
print()

# 모든 행과 두 번째 열을 선택합니다.
print(matrix[:,1:2])

3

5

[1 2 3 4 5 6]

[1 2 3]

[4 5 6]

6

[[1 2 3]
 [4 5 6]]

[[2]
 [5]
 [8]]


## 슬라이싱

In [9]:
import numpy
ar = numpy.array([1,2,3,4,5])
#복제된 데이터가 아니고 현재 데이터의 포인터만 가져옴
br = ar[0:3]

#복제된 데이터
cr = ar[0:3].copy()

#원본 데이터 변경
ar[0]=10
print(ar)
print()

#복제된 데이터가 아니므로 원본 데이터의 변경이 반영됨
print(br)
print()

#복제된 데이터 이므로 반영되지 않음
print(cr)

[10  2  3  4  5]

[10  2  3]

[1 2 3]


## Fancy Indexing

In [10]:
import numpy

ar = numpy.empty((10, 5)) #gabage 값을 갖는 10행 5열의 배열을 생성
for i in range(10):
    ar[i] = i   #각 행의 모든 데이터를 i 값으로 채움
print(ar)
print()

br = ar[[1,3,5,7]] #1,3,5,7 행만 선택
print(br)
print()

cr = ar[[0,1], [3,4]] #[0,3],[1,4] 만 선택
print(cr)
print()

dr = ar[[0,1]][:,[3,4]] #0번 행의 3번째와 4번째 1번 행의 3번째와 4번째 데이터 선택
print(dr)
print()

#fancy 색인은 copy 이므로  ar의 내용이 변경되더라도 dr은 변경이 없음
ar[0,3] = 100
print(dr)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9.]]

[[1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [5. 5. 5. 5. 5.]
 [7. 7. 7. 7. 7.]]

[0. 1.]

[[0. 0.]
 [1. 1.]]

[[0. 0.]
 [1. 1.]]


In [11]:
ar = numpy.empty((10, 5)) #gabage 값을 갖는 10행 5열의 배열을 생성
for i in range(10):
    ar[i] = i   #각 행의 모든 데이터를 i 값으로 채움
#일차원 배열로 리턴
print(ar[0])
print()

print(ar[0, :])
print()

#이차원 배열로 리턴
print(ar[[0]])

[0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]]


## 불리언 색인

In [12]:
import numpy
ar = numpy.arange(20).reshape(5, 4)
br = numpy.array(['A', "B", 'C', 'A', 'C'])
print(br == 'A') #데이터가 A인 경우는 True 그렇지 않으면 False
print()
print(ar[br == 'A']) #True 인 행만 반환
print()
print(ar[br == 'A', 2]) #열을 2번째만 반환
print()
print(ar[br == 'A', 0:2]) #열을 0부터 2앞까지 반환
print()
#데이터 변환
ar[br == 'A'] = 100
print(ar)
print()
print( (br == 'A') | (br == 'B') )

[ True False False  True False]

[[ 0  1  2  3]
 [12 13 14 15]]

[ 2 14]

[[ 0  1]
 [12 13]]

[[100 100 100 100]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 100 100 100]
 [ 16  17  18  19]]

[ True  True False  True False]


## ndarray의 연산

In [13]:
import numpy
ar = numpy.array([1,2,3])
br = numpy.array([4,5,6])
cr = numpy.array([[6,7,8], [10,20,30]])
result = ar * 2 #배열의 모든 요소에 2를 곱한 결과
print(result)
print()

result = ar + br; #배열 간의 덧셈: 동일한 위치간의 덧셈을 한 결과
print(result)
print()

result = ar + cr #작은 차원인 ar 의 모든 데이터를 cr에 덧셈
print(result)
print()

dr = numpy.array([1,2])
result = ar + dr #차원은 1차원으로 같은데 데이터 개수가 달라서 에러

[2 4 6]

[5 7 9]

[[ 7  9 11]
 [11 22 33]]



ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## 배열의 모든 요소에 동일한 함수 적용

In [14]:
#벡터화된 연산
import numpy 

# 행렬을 만듭니다.
matrix = numpy.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 100을 더하는 함수를 생성
add_100 = lambda i: i + 100

# 벡터화된 함수를 만듭니다.
vectorized_add_100 = numpy.vectorize(add_100)

# 행렬의 모든 원소에 함수를 적용합니다.
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## ndarray의 논리 연산

In [15]:
import numpy
ar = numpy.array([1,2,3])
br = numpy.array([4,2,6])

#각 요소가 같은지 비교
print(numpy.equal(ar, br))
print(ar == br)
print()

#각 요소가 다른지 비교
print(numpy.not_equal(ar, br))
print(ar != br)
print()

#ar의 요소가 큰지 확인
print(numpy.greater(ar, br))
print(numpy.greater_equal(ar, br))
print()

#ar의 요소가 작은지 확인
print(numpy.less(ar, br))
print(numpy.less_equal(ar, br))

[False  True False]
[False  True False]

[ True False  True]
[ True False  True]

[False False False]
[False  True False]

[ True False  True]
[ True  True  True]


In [16]:
import numpy
ar = numpy.array([1,0,3])
br = numpy.array([4,2,3])

#논리 연산
print(numpy.logical_and(ar, br))
print(numpy.logical_or(ar, br))
print(numpy.logical_xor(ar, br))
print()

#데이터의 소속 여부 확인
print(1 in ar)
print(2 in ar)

[ True False  True]
[ True  True  True]
[False  True False]

True
False


## 배열의 전치 와 축 변경

In [17]:
ar = numpy.arange(15).reshape((3, 5))
print(ar)
print()

print(ar.T)
print()

print(ar.transpose(1,0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## 난수

In [18]:
import numpy
print(numpy.random.normal(size=5)) #5개의 난수 생성 - 랜덤
print()
print(numpy.random.normal(size=(2, 3))) #2행 3열의 난수 생성
print()
numpy.random.seed(seed=42) #시드 설정
print(numpy.random.normal(size=5)) #5개의 난수 생성 - 실행할 때마다 동일한 값

[-1.38115194  0.01269875 -1.5817729   1.77950526 -0.21296055]

[[-0.95391575  0.501173   -0.66573728]
 [-1.86067898  2.26492081 -1.7178524 ]]

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


## 기본 통계 함수

In [19]:
import numpy
ar = numpy.array([1, 2, 4, 5, 5, 7, 9, 10, 13, 18, 21])
print('배열의 합계:', numpy.sum(ar))
print('배열의 평균:', numpy.mean(ar))
print('배열의 중간값:', numpy.median(ar))
print('배열의 표준편차:', numpy.std(ar))
print('배열의 분산:', numpy.var(ar))
print('배열에서 3/4에 해당하는 값:', numpy.percentile(ar, 75))

배열의 합계: 95
배열의 평균: 8.636363636363637
배열의 중간값: 7.0
배열의 표준편차: 6.138888369503321
배열의 분산: 37.68595041322314
배열에서 3/4에 해당하는 값: 11.5


In [20]:
import numpy
#print(help(numpy.sum))

ar = numpy.array([[1, 2, 4, 5, 5], [7, 9, 10, 13, 18]])
#배열 전체의 합계
print(numpy.sum(ar))
print('===============')
#열 단위의 합계
print(numpy.sum(ar, axis=0))
print('===============')
#행 단위의 합계
print(numpy.sum(ar, axis=1))

74
[ 8 11 14 18 23]
[17 57]


In [21]:
import numpy

# 행렬을 만듭니다.
matrix = numpy.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 각 행에서 최댓값
print(numpy.max(matrix, axis=1))
print()

#결과가 동일한 차원의 배열
print(numpy.max(matrix, axis=1, keepdims=True))

[3 6 9]

[[3]
 [6]
 [9]]


In [22]:
ar = numpy.random.randn(100)
print(ar)
print()
print((ar > 0).sum())

[-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769
 -0.46572975  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112
  0.31424733 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282
 -1.42474819 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869
 -0.29169375 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491
 -1.22084365  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658
  0.17136828 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877
  1.05712223  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922
  0.61167629  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343
  0.97554513 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582
  1.35624003 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561
  1.53803657 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707
 -0.29900735  0.09176078 -1.98756891 -0.21967189  0.35711257  1.47789404
 -0.51827022 -0.8084936  -0.50175704  0.91540212  0.32

## 배열 기술 통계

In [23]:
import numpy
b = numpy.array([1, 2, 3, 4])
c = numpy.array([[1, 2], [3, 4]])
print(numpy.prod(b)) # 1*2*3*4
print(numpy.prod(c, axis=0))  # [1*3, 2*4]
print(numpy.prod(c, axis=1))  # [1*2, 3*4]
print(numpy.sum(b)) # [1+2+3+4]
print(numpy.sum(b, keepdims=True))
print(numpy.sum(c, axis=0))  # [1+3, 2+4]
print(numpy.sum(c, axis=1) ) # [1+2, 3+4]

24
[3 8]
[ 2 12]
10
[10]
[4 6]
[3 7]


In [24]:
import numpy
b = numpy.array([1, 2, 3, 4])
c = numpy.array([[1, 2], [3, 4]])
print(numpy.cumprod(b))# [1, 1*2, 1*2*3, 1*2*3*4]
print(numpy.cumprod(c, axis=0))  # [[1, 2], [1*3, 2*4]]
print(numpy.cumprod(c, axis=1))  # [[1, 1*2], [3, 3*4]]
print(numpy.cumsum(b))# [1, 1+2, 1+2+3, 1+2+3+4]
print(numpy.cumsum(c, axis=0))  # [[1, 2], [1+3, 2+4]]
print(numpy.cumsum(c, axis=1))  # [[1, 1+2], [3, 3+4]]

[ 1  2  6 24]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [25]:
import numpy
g = numpy.array([1, 2, 4, 10, 13, 20])
print(numpy.diff(g))  # [2-1, 4-2, 10-4, 13-10, 20-13]
print(numpy.diff(g, n=2))  # [2-1, 6-2, 3-6, 7-3]

[1 2 6 3 7]
[ 1  4 -3  4]


## 소수 관련 함수

In [26]:
import numpy
ar = numpy.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print(numpy.around(ar))
print(numpy.round_(ar, 1))
print(numpy.rint(ar))
print(numpy.fix(ar))
print(numpy.ceil(ar))
print(numpy.floor(ar))
print(numpy.trunc(ar))

[-5. -2.  0.  2.  3.  4.]
[-4.6 -2.2  0.   1.6  3.4  4.1]
[-5. -2.  0.  2.  3.  4.]
[-4. -2.  0.  1.  3.  4.]
[-4. -2.  0.  2.  4.  5.]
[-5. -3.  0.  1.  3.  4.]
[-4. -2.  0.  1.  3.  4.]


## 논리 함수

In [27]:
import numpy
ar = numpy.array([10, 1, 2, 3, 4, numpy.nan])
print(numpy.isnan(ar)) #isnan을 이용해서 nan 데이터가 있는지 확인
br = ar[numpy.logical_not(numpy.isnan(ar))] #nan 데이터를 제외하고 가져오기
print(br)
print(numpy.logical_not( br <= 2 )) #2보다 큰 데이터가 있는지 확인
cr = br[numpy.logical_not( br <= 2 )] #2보다 큰 데이터 추출
print(cr)

[False False False False False  True]
[10.  1.  2.  3.  4.]
[ True False False  True  True]
[10.  3.  4.]


## 이항 함수

In [28]:
import numpy
ar = numpy.array([1, 2, 3, 4])
br = numpy.array([5, 6, 7, 8])
print(ar + br)
print(numpy.add(ar, br))
cond = [True, False, False, True]
print(numpy.where(cond, ar, br))

[ 6  8 10 12]
[ 6  8 10 12]
[1 6 7 4]


## 집합 관련 함수

In [29]:
import numpy
ar = numpy.array([90, 40, 30, 78, 30])
#중복 제거
print("중복제거:", numpy.unique(ar))
br = numpy.array([30, 45, 76, 90])
#교집합
print('교집합:', numpy.intersect1d(ar, br))
#합집합
print('합집합:',numpy.union1d(ar, br))
#소속여부
print('소속여부:',numpy.in1d(ar, br))
#차집합
print('차집합',numpy.setdiff1d(ar, br))
#한쪽에만 속한 데이터
print(numpy.setxor1d(ar, br))

중복제거: [30 40 78 90]
교집합: [30 90]
합집합: [30 40 45 76 78 90]
소속여부: [ True False  True False  True]
차집합 [40 78]
[40 45 76 78]


## ndarray 정렬

In [30]:
import numpy
ar = numpy.array([90, 40, 30, 78])
ar.sort()
print(ar)
print()

br = numpy.sort(ar)
print(br)
print()

# 내림차순
cr = numpy.sort(ar)[::-1]
print(cr)
print()

ar.sort(kind='mergesort')
print(ar)
print()

ar = numpy.array([[90, 40, 50], [30, 78,27]])
ar.sort(axis=0)
print(ar)

[30 40 78 90]

[30 40 78 90]

[90 78 40 30]

[30 40 78 90]

[[30 40 27]
 [90 78 50]]


## 배열 분할

In [32]:
import numpy
ar = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(ar)
print()
splitY = numpy.split(ar, 2, axis = 0) #x축 방향으로 2개로 나눔
print(splitY[0])
print(splitY[1])
print()
splitX = numpy.split(ar, [2, 3], axis = 1) #2번째 앞까지 나누고 3번째 앞까지 나누고 나머지
print(splitX[0])
print(splitX[1])
print(splitX[2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


## 배열의 결합

In [ ]:
import numpy
ar = [1,2,3,4]
br = [5,6,7,8]
cr = numpy.concatenate((ar, br))
print(cr)
print()

ar = numpy.array([[1, 2], [3, 4]])
br = numpy.array([[5, 6], [7, 8]])
cr = numpy.concatenate((ar, br), axis = 0)
print(cr)
print()

cr = numpy.concatenate((ar, br), axis = 1)
print(cr)

In [34]:
#hstack: 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 생성
import numpy
a1 = numpy.ones((2, 3))
print(a1)
print()

a2 = numpy.zeros((2, 2))
print(a2)
print()

print(numpy.hstack([a1, a2]))

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [35]:
#vstack: 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열 생성
import numpy
a1 = numpy.ones((2, 2))
print(a1)
print()

a2 = numpy.zeros((2, 2))
print(a2)
print()

print(numpy.vstack([a1, a2]))


[[1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [36]:
#dstack
import numpy
c1 = numpy.array(range(1,13,1))
c2 = c1.reshape(3,4)
print(c2)
print()

d1 = numpy.array(range(101,113,1))
d2 = d1.reshape(3,4)
print(d2)
print()

print(numpy.dstack([c2, d2]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]

[[[  1 101]
  [  2 102]
  [  3 103]
  [  4 104]]

 [[  5 105]
  [  6 106]
  [  7 107]
  [  8 108]]

 [[  9 109]
  [ 10 110]
  [ 11 111]
  [ 12 112]]]


In [37]:
# stack
print(numpy.stack([c2, d2]))

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[101 102 103 104]
  [105 106 107 108]
  [109 110 111 112]]]


In [38]:
print(numpy.stack([c2, d2], axis=1))

[[[  1   2   3   4]
  [101 102 103 104]]

 [[  5   6   7   8]
  [105 106 107 108]]

 [[  9  10  11  12]
  [109 110 111 112]]]


In [39]:
# r_
print(numpy.r_[numpy.array([1, 2, 3]), numpy.array([4, 5, 6])])


[1 2 3 4 5 6]


In [40]:
# c_
print(numpy.c_[numpy.array([1, 2, 3]), numpy.array([4, 5, 6])])


[[1 4]
 [2 5]
 [3 6]]


In [41]:
#tile
a = numpy.array([[0, 1, 2], [3, 4, 5]])
print(numpy.tile(a, 2))
print()
print(numpy.tile(a, (3, 2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


## 배열의 데이터 저장 과 가져오기

In [42]:
ar = numpy.array([[0, 1, 2], [3, 4, 5]])
#파일로 저장
numpy.save('some_array.npy', ar)
#파일에서 읽어오기
print(numpy.load('some_array.npy'))
print()

br = numpy.arange(10)
numpy.savez('array_archive.npz', ar=ar, br=br)
print(numpy.load('array_archive.npz')['br'])

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5 6 7 8 9]
